name: Codestyle checks

on: [ push, pull_request, workflow_dispatch ]

jobs:
  codestyle:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setting up Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements_linux.txt
          python -m pip install pytest-pylint pytest-flake8
      - name: Running flake8 checks
        run: python -m flake8 ./ --config=setup.cfg --show-source --statistics

      - name: Running pylint checks
        run: python -m mypy ./ --config-file ./setup.cfg --show-error-context --show-column-numbers --pretty